services:
    th3mouk_cms_static_content.admin.static_content:
        class: Th3Mouk\CMSSimpleContentManagerBundle\Admin\ContentAdmin
        arguments: [~, Th3Mouk\CMSSimpleContentManagerBundle\Entity\Content, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: static_content}
        calls:
            - [ setTranslationDomain, ["Content"]]
